### ISSUE TITLE
Unused assert_not_zero import ex02

### ISSUE THREAD

**Issue by Magicking** [l-henri/starknet-cairo-101#14]
It seems that the imported math function `assert_not_zero` referenced in these exercises is not used anywhere.
https://github.com/l-henri/starknet-cairo-101/blob/295b235812412985edc6d82c80d53b6d7b336790/contracts/ex02.cairo#L25
https://github.com/l-henri/starknet-cairo-101/blob/295b235812412985edc6d82c80d53b6d7b336790/contracts/ex03.cairo#L23

Am-I wrong or is it something that might be removed?

**Comment by l-henri** [comment]
Correct! Will remove it, thanks!
