### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ayushm2003** [l-henri/starknet-cairo-101#2]
hey,

https://github.com/l-henri/starknet-cairo-101/blob/main/contracts/ex02.cairo#L38
> It can be read wtht my_secret_value_storage.read() or written to with my_secret_value_storage.write()

does this line mean that it can be read/written to from _inside_ the contract? worth specifying that, if that's the case.

also, is there any group that I can join to clarify some of my general doubts?

**Comment by l-henri** [comment]
Hello! Sure, will add this.
You can join our Discord https://discord.gg/YHz7drT3 in channel #tutorials-support
Thank you!
